In [0]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import pandas as pd

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D, Lambda, MaxPool2D, BatchNormalization
from keras.utils import np_utils
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import Adam
import pydot
import graphviz
from keras.utils.vis_utils import model_to_dot
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import xml.etree.ElementTree as ET
from keras.utils import plot_model
import sklearn
import itertools
import cv2
import scipy
import os
import csv
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [17]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# 2. Save Keras Model or weights on google drive

# create on Colab directory
model.save('model.h5')    
model_file = drive.CreateFile({'title' : 'model.h5'})
model_file.SetContentFile('model.h5')
model_file.Upload()

# download to google drive
drive.CreateFile({'id': model_file.get('id')})

    100% |████████████████████████████████| 993kB 20.7MB/s 


GoogleDriveFile({'id': '19ms83W_-c8Gi3fiJqkBlpQV8VdZ8jloz'})

In [3]:
from google.colab import files
uploaded = files.upload()

Saving keras_classification_wbc - Sheet1 (1).csv to keras_classification_wbc - Sheet1 (1).csv


In [18]:
import pandas as pd
import io

dataset = pd.read_csv(io.StringIO(uploaded['keras_classification_wbc - Sheet1 (1).csv'].decode('utf-8')))
dataset

age  gender  lymphocyte  neutrophil count  easonophil  monocyte   \
0     62       1           3                 2           2          1   
1     63       1           3                 2           2          1   
2     68       1           3                 2           2          1   
3     61       1           3                 2           2          1   
4     60       1           3                 2           2          1   
5     65       1           3                 2           2          1   
6     60       0           3                 1           2          2   
7     65       0           3                 1           2          2   
8     62       0           3                 1           2          2   
9     63       0           3                 1           2          2   
10    61       0           3                 1           2          2   
11    66       0           3                 1           2          2   
12    40       1           3                 2           2          1   
13    41       1           3                 2           2          1   
14    45       1           3                 2           2          1   
15    49       1           3                 2           2          1   
16    50       1           3                 2           2          1   
17    42       1           3                 2           2          1   
18    60       1           3                 2           2          1   
19    61       0           1                 3           2          2   
20    65       0           1                 3           2          2   
21    67       0           1                 3           2          2   
22    68       0           1                 3           2          2   
23    59       0           1                 3           2          2   
24    62       0           1                 3           2          2   
25    63       0           1                 3           2          2   
26    64       0           1                 3           2          2   
27    60       1           3                 2           2          1   
28    59       1           3                 2           2          1   
29    58       1           3                 2           2          1   
..   ...     ...         ...               ...         ...        ...   
78    65       1           1                 3           2          2   
79    15       1           3                 1           2          2   
80    16       1           3                 1           2          2   
81    17       1           3                 1           2          2   
82    18       1           3                 1           2          2   
83    19       1           3                 1           2          2   
84    20       1           3                 1           2          2   
85    21       1           3                 1           2          2   
86    22       1           3                 1           2          2   
87    23       1           3                 1           2          2   
88    24       1           3                 1           2          2   
89    25       1           3                 1           2          2   
90    26       1           3                 1           2          2   
91    27       1           3                 1           2          2   
92    28       1           3                 1           2          2   
93    29       0           2                 1           2          3   
94    14       1           2                 1           2          3   
95    15       1           2                 1           2          3   
96    16       1           2                 1           2          3   
97    17       0           2                 1           2          3   
98    18       1           2                 1           2          3   
99    19       0           2                 1           2          3   
100   20       0           2                 1           2     

In [22]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np
import os

from google.colab import files
GOOGLE_COLAB=True
MFILE97='model_disease_prediction6.h5'

#Splitting the data into training and test
X = dataset.iloc[:,0:6].values
y = dataset.iloc[:,6].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
Y = pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

model = Sequential()

model.add(Dense(6,input_shape=(6,),activation='sigmoid'))
#model.add(Dropout(0.5))
#model.add(Dense(8,activation='tanh'))
#model.add(Dense(6,activation='tanh'))
model.add(Dense(9,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

#model.summary()

model.fit(X_train,y_train,epochs=100)
model.save(MFILE97)  

Epoch 1/100
86/86 [==============================] - 0s 5ms/step - loss: 2.6188 - acc: 0.0698
Epoch 2/100
86/86 [==============================] - 0s 104us/step - loss: 2.3682 - acc: 0.0698
Epoch 3/100
86/86 [==============================] - 0s 83us/step - loss: 2.2329 - acc: 0.1512
Epoch 4/100
86/86 [==============================] - 0s 98us/step - loss: 2.1305 - acc: 0.1628
Epoch 5/100
86/86 [==============================] - 0s 80us/step - loss: 2.0829 - acc: 0.1628
Epoch 6/100
86/86 [==============================] - 0s 74us/step - loss: 2.0325 - acc: 0.2791
Epoch 7/100
86/86 [==============================] - 0s 75us/step - loss: 1.9667 - acc: 0.2791
Epoch 8/100
86/86 [==============================] - 0s 70us/step - loss: 1.8975 - acc: 0.3140
Epoch 9/100
86/86 [==============================] - 0s 70us/step - loss: 1.8269 - acc: 0.3023
Epoch 10/100
86/86 [==============================] - 0s 72us/step - loss: 1.7653 - acc: 0.3256
Epoch 11/100
86/86 [=============================

In [23]:
#X
#y
y1
#Y
#len(X_test)

array([3, 3, 3, 3, 3, 3, 6, 6, 6, 6, 6, 6, 2, 2, 2, 2, 2, 2, 2, 7, 7, 7,
       7, 7, 7, 7, 7, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 7, 7, 7, 7,
       7, 7, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 8, 8, 8, 8, 8, 8])

In [0]:
from google.colab import files
files.download('model_disease_prediction6.h5')

In [0]:
from keras.models import load_model  #loading saved model works
new_model1=load_model('model_disease_prediction6.h5')

In [16]:
new_model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_4 (Dense)              (None, 9)                 63        
Total params: 105
Trainable params: 105
Non-trainable params: 0
_________________________________________________________________


In [0]:
y_pred = model.predict(X_test)
y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

In [0]:
y_pred

array([[6.00985150e-05, 1.38891982e-02, 9.99923097e-04, 1.70132698e-05,
        9.21182521e-03, 9.75433946e-01, 2.85550981e-04, 2.82120851e-08,
        1.02433041e-04],
       [1.03350300e-02, 1.20822340e-02, 7.28154206e-04, 2.05132775e-02,
        6.18735930e-06, 7.15886569e-03, 9.48531330e-01, 6.10147486e-04,
        3.47064342e-05],
       [5.52427053e-01, 7.45011261e-03, 8.96982907e-04, 8.52706376e-03,
        6.04784524e-04, 8.25702809e-05, 3.93340411e-03, 4.01142597e-01,
        2.49353703e-02],
       [1.21519700e-01, 1.11163885e-04, 3.16174813e-02, 8.31925094e-01,
        1.00868579e-04, 1.79464419e-04, 1.03036379e-02, 3.78604583e-03,
        4.56490932e-04],
       [7.82244653e-02, 4.80789784e-03, 2.81032135e-06, 4.36957380e-05,
        5.50133736e-05, 2.22648669e-06, 2.68940552e-04, 9.07936394e-01,
        8.65846034e-03],
       [4.52377921e-04, 9.82961595e-01, 1.34284960e-06, 2.96084792e-08,
        7.53306667e-04, 1.01904944e-02, 4.97654401e-05, 1.10214678e-05,
        5.5

In [0]:
X_test2 = np.array([[16, 1,3,1,2,2],[40,1,3,2,2,1],[34,0,1,3,2,2]])
y_pred2 = new_model1.predict(X_test2)
y_pred2

array([[3.06550937e-05, 1.24907615e-02, 4.90380859e-04, 6.15237332e-06,
        1.29763586e-02, 9.73767281e-01, 1.60291733e-04, 2.05090736e-08,
        7.80787595e-05],
       [1.33491438e-02, 7.05527418e-05, 9.60011601e-01, 1.68972500e-02,
        5.17325662e-03, 1.29437214e-03, 2.84589205e-05, 2.02236583e-06,
        3.17341462e-03],
       [1.11672722e-01, 4.06413265e-02, 6.23213477e-04, 1.12345651e-05,
        1.95819605e-02, 1.83216209e-04, 5.35503341e-06, 3.19158612e-03,
        8.24089408e-01]], dtype=float32)

In [0]:
print(np.argmax(y_pred2,axis=1))

[5 2 8]
